class AppStrings {
  static String appname = "mediappoint",
      bestDocapp = "Best Doctor\n Appointment App",
      welcomeBack = "Welcome Back!",
      weAreExcited = "We're excited to have you back!",
      signupNow =
          "Sign up now and start exploring all that our app has to offer.",
      email = "Email",
      emailHint = "Enter your email...",
      password = "Password",
      passswordHint = "Enter your password here(Atleast 6 charcters)",
      forgetpassword = "Forget Password?",
      fullname = "Full Name",
      fullnameHint = "Enter your name here...",
      doctor = "Doctor Login",
      category = "Category",
      settings = "Settings",
      confirmpassword = "Confirm Password",
      login = "Login",
      signup = "Signup",
      welcome = "Welcome",
      search = "Search Doctor",
      alreadyHaveAccount = "Already have an account?",
      dontHaveAccount = "Don't have an account?",
      body = "Body",
      ear = "Ear",
      eye = "Eye",
      heart = "Heart",
      kidney = "Kidney",
      liver = "Liver",
      lungs = "Lungs",
      stomach = "Stomach",
      tooth = "Tooth",
      changepassword="Change Password",
      tnc="Terms & Conditions",
      signout="Signout"
      ;
}
